import type { Metadata } from "next";
import Link from "next/link";

import { CalloutNote, H2, H3, Li, LegalLayout, P, Strong, Ul } from "@/components/marketing/legal-doc";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Study Planner collects, uses, and protects your personal data.",
};

const SECTIONS = [
  ["who-we-are", "1. Who we are"],
  ["what-we-collect", "2. What data we collect"],
  ["how-we-use-it", "3. How we use your data, and why we’re allowed to"],
  ["ai-processing", "4. AI features specifically"],
  ["who-we-share-with", "5. Who we share your data with"],
  ["international-transfers", "6. International data transfers"],
  ["retention", "7. How long we keep your data"],
  ["security", "8. Security"],
  ["your-rights", "9. Your rights"],
  ["cookies", "10. Cookies and similar technologies"],
  ["children", "11. Children’s privacy"],
  ["changes", "12. Changes to this policy"],
  ["contact", "13. Contact and complaints"],
] as const;

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout
      title="Privacy Policy"
      lastUpdated="September 28, 2026"
      intro={
        <>
          <p>
            This policy explains what personal data Study Planner collects, why, and what
            rights you have over it — including under the EU/UK General Data Protection
            Regulation (GDPR). It’s written to describe what the product actually does, not
            as generic boilerplate.
          </p>
          <nav aria-label="Sections" className="mt-6 text-sm">
            <ul className="grid grid-cols-1 gap-x-6 gap-y-1 sm:grid-cols-2">
              {SECTIONS.map(([id, label]) => (
                <li key={id}>
                  <a href={`#${id}`} className="hover:text-foreground underline underline-offset-2">
                    {label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </>
      }
    >
      <CalloutNote>
        <Strong>Before this goes live:</Strong> this document is a thorough draft grounded in
        the actual codebase, not a certified legal document. Fill in the bracketed placeholders
        below (data controller identity, jurisdiction, contact address) and have it reviewed by
        someone qualified to advise on GDPR compliance in your jurisdiction before you rely on
        it with real users’ data.
      </CalloutNote>

      <H2 id="who-we-are">1. Who we are</H2>
      <P>
        Study Planner (&ldquo;we&rdquo;, &ldquo;us&rdquo;) is the data controller for the
        personal data described in this policy. We are currently operated by{" "}
        <Strong>[your name or company name]</Strong>, based in{" "}
        <Strong>[your country/jurisdiction]</Strong>. You can reach us at{" "}
        <Strong>[privacy contact email]</Strong>.
      </P>
      <P>
        Study Planner is a study-planning application for students and working professionals:
        it combines your courses, deadlines, and fixed commitments into a schedule, and offers
        optional AI-assisted explanations, task breakdowns, and course-document extraction.
      </P>

      <H2 id="what-we-collect">2. What data we collect</H2>
      <P>We collect data you give us directly, and data generated by using the product.</P>

      <H3>Account and profile</H3>
      <Ul>
        <Li>Name, email address, and password (your password is hashed by our authentication provider — we never see or store it in plain text).</Li>
        <Li>Time zone, language preference, and whether you use the app as a student or a working professional (this only changes default settings, never what data we collect).</Li>
      </Ul>

      <H3>Academic and planning data</H3>
      <Ul>
        <Li>Institutions, degree programs, and courses you add (name, code, difficulty, priority, target grade, estimated weekly hours).</Li>
        <Li>Tasks, deadlines, exams, and to-dos, including any subtasks.</Li>
        <Li>Calendar events you add manually or import, and — if you connect Google Calendar — events read from that calendar. Google account tokens are encrypted at rest and never readable by the application’s normal database access, only by the specific server process that needs them to sync.</Li>
        <Li>Your study preferences (session length, daily limits, available hours, break style) and the study plans and individual study sessions generated from them.</Li>
        <Li>If you upload a course document (a syllabus, schedule, or assessment guide): the original file, and the structured information (assessments, dates, requirements) extracted from it.</Li>
      </Ul>

      <H3>Study groups</H3>
      <Ul>
        <Li>If you join or create a study group: the group’s name, your membership, and your adherence score (how much of your own plan you kept — never grades, and never compared to other members on anything except that one shared metric, at the sharing level you choose).</Li>
      </Ul>

      <H3>Technical and usage data</H3>
      <Ul>
        <Li>Standard web request data (IP address, browser type, device type) collected by our hosting provider for security and abuse prevention.</Li>
        <Li>We do not currently use third-party analytics, advertising, or tracking tools. If that changes, this policy — and, where legally required, a consent mechanism — will change with it.</Li>
      </Ul>

      <H2 id="how-we-use-it">3. How we use your data, and why we&rsquo;re allowed to</H2>
      <P>
        Under GDPR, we need a lawful basis for each way we use your data. Here is ours, mapped
        to what we actually do:
      </P>
      <Ul>
        <Li>
          <Strong>Performance of a contract</Strong> (Art. 6(1)(b)) — creating your account,
          storing your courses and deadlines, generating and adjusting your study plan,
          rendering your calendar, and every other core feature you signed up to use. Most of
          what this app does falls here.
        </Li>
        <Li>
          <Strong>Legitimate interests</Strong> (Art. 6(1)(f)) — securing the service against
          abuse, debugging errors, and maintaining an audit log of sensitive account actions
          (exports, deletions, integrations connected or removed), balanced against your right
          to privacy. We don’t use this basis for anything that would surprise you.
        </Li>
        <Li>
          <Strong>Consent</Strong> (Art. 6(1)(a)) — connecting an optional third-party
          integration (Google Calendar) or turning on an optional AI feature is something you
          actively choose to do, and you can disconnect or stop at any time from Settings.
        </Li>
        <Li>
          <Strong>Legal obligation</Strong> (Art. 6(1)(c)) — where we’re required to keep or
          disclose specific records by law.
        </Li>
      </Ul>
      <P>We do not sell your personal data, and we do not use it to serve you advertising.</P>

      <H2 id="ai-processing">4. AI features specifically</H2>
      <P>
        Some features send data to a third-party AI provider to generate a response: explaining
        why your plan looks the way it does, breaking a task into subtasks, answering a question
        you ask the planning advisor, or reading an uploaded course document to propose
        structured assessments and dates.
      </P>
      <Ul>
        <Li>
          Only the data a specific feature needs is sent — for example, explaining a plan sends
          the plan’s sessions and reasons, not your whole account history.
        </Li>
        <Li>
          <Strong>Every AI feature proposes; none of them decide.</Strong> A plan explanation is
          just text. A task breakdown is a list you tick and approve before anything is saved. A
          course document’s extracted assessments and dates are shown to you for review — with a
          confidence level and a link back to the source page — and nothing is written to your
          account until you confirm it. No AI output in this product takes an action on your
          account by itself, and nothing here makes an automated decision about you with a
          legal or similarly significant effect (GDPR Art. 22).
        </Li>
        <Li>
          The advisor is the one place your own free-text messages reach a model. Messages are
          used only to generate that reply; they are not used to train the AI provider’s models
          under our agreements with them.
        </Li>
        <Li>
          If you disable AI features or your account has no AI provider configured, the product
          continues to work — the planning engine itself never depends on AI.
        </Li>
      </Ul>

      <H2 id="who-we-share-with">5. Who we share your data with</H2>
      <P>
        We use a small number of service providers (sub-processors) to run the product. Each
        one processes your data only to provide their specific service to us, under a data
        processing agreement.
      </P>
      <Ul>
        <Li><Strong>Supabase</Strong> — our database, authentication, and file storage provider. This is where your account data, academic data, and uploaded documents live.</Li>
        <Li><Strong>[OpenAI, L.L.C. and/or Anthropic PBC]</Strong> — whichever AI provider is configured processes the specific request data described in §4, for the features you use.</Li>
        <Li><Strong>Google LLC</Strong> — only if you connect Google Calendar, to read your calendar events.</Li>
        <Li><Strong>[Vercel Inc. — once deployed]</Strong> — application hosting.</Li>
      </Ul>
      <P>
        We do not share your data with anyone else, except where required by law or to protect
        our legal rights.
      </P>

      <H2 id="international-transfers">6. International data transfers</H2>
      <P>
        Some of the providers above may process data outside the EU/EEA or UK, including in the
        United States. Where that happens, we rely on the safeguards recognised under GDPR —
        typically Standard Contractual Clauses — to protect your data to the same standard it
        would receive within the EU/EEA.
      </P>

      <H2 id="retention">7. How long we keep your data</H2>
      <P>
        We keep your data for as long as your account is active. If you delete your account,
        deletion is <Strong>immediate and permanent</Strong> — the underlying database
        relationships mean every table holding your data is removed in one action, not merely
        marked inactive. Nothing lingers in a &ldquo;soft-deleted&rdquo; state waiting to be purged later.
      </P>
      <P>
        Some narrow exceptions: records we’re legally required to retain (e.g. for tax or fraud-
        prevention purposes, if applicable) are kept only as long as that legal requirement
        lasts, and are excluded from normal account access once your account is gone.
      </P>

      <H2 id="security">8. Security</H2>
      <P>Concretely, not just as a promise:</P>
      <Ul>
        <Li>Every table in our database enforces row-level security — the database itself refuses to return another user’s row, not just the application code.</Li>
        <Li>Third-party integration tokens (e.g. Google Calendar) are encrypted at rest with AES-256-GCM, and are not readable through the normal application database connection at all.</Li>
        <Li>Passwords are hashed by our authentication provider; we never see or store a plain-text password.</Li>
        <Li>Data in transit is encrypted (HTTPS/TLS).</Li>
      </Ul>
      <P>No system is perfectly secure, but these are real, verifiable controls, not marketing language.</P>

      <H2 id="your-rights">9. Your rights</H2>
      <P>If GDPR applies to you, you have the right to:</P>
      <Ul>
        <Li><Strong>Access</Strong> the personal data we hold about you.</Li>
        <Li><Strong>Rectify</Strong> inaccurate data — most of it you can correct yourself, directly in the app.</Li>
        <Li><Strong>Erase</Strong> your data (&ldquo;right to be forgotten&rdquo;) — self-service, from Settings → Privacy, with immediate effect.</Li>
        <Li><Strong>Export</Strong> your data in a portable format — also self-service, from the same page.</Li>
        <Li><Strong>Restrict or object to</Strong> certain processing.</Li>
        <Li><Strong>Withdraw consent</Strong> at any time, for anything based on consent (e.g. disconnect Google Calendar).</Li>
        <Li><Strong>Lodge a complaint</Strong> with your local data protection supervisory authority — see §13.</Li>
      </Ul>
      <P>
        You can exercise most of these rights yourself, in-app, right now:{" "}
        <Link href="/settings" className="hover:text-foreground underline underline-offset-2">
          Settings → Privacy
        </Link>
        . For anything else, contact us using the details in §13.
      </P>

      <H2 id="cookies">10. Cookies and similar technologies</H2>
      <P>We keep this deliberately minimal:</P>
      <Ul>
        <Li><Strong>Essential:</Strong> an authentication session cookie, so you stay signed in. Without it, the app cannot function.</Li>
        <Li><Strong>Functional:</Strong> a cookie remembering your chosen language.</Li>
        <Li><Strong>Local device storage:</Strong> your light/dark theme preference is stored only in your browser (not a cookie, and never sent to our servers).</Li>
      </Ul>
      <P>
        We do not use advertising or cross-site tracking cookies. Because the cookies above are
        essential or strictly functional, they don’t require the kind of consent banner used for
        tracking or advertising cookies — but if that ever changes, this section changes with it.
      </P>

      <H2 id="children">11. Children&rsquo;s privacy</H2>
      <P>
        Study Planner is intended for users aged 16 and over, consistent with GDPR’s default
        digital consent age (some countries set this lower, down to 13 — see the actual rule in
        your country if you’re near this boundary). We do not knowingly collect data from
        children below the applicable age without appropriate consent. If you believe a child
        has created an account without the required consent, contact us and we’ll remove it.
      </P>

      <H2 id="changes">12. Changes to this policy</H2>
      <P>
        If we make a material change to how we handle your data, we’ll update the date at the
        top of this page and, for significant changes, tell you directly (e.g. by email or an
        in-app notice) before the change takes effect.
      </P>

      <H2 id="contact">13. Contact and complaints</H2>
      <P>
        Questions about this policy, or want to exercise a right not covered by the self-service
        tools in Settings? Contact us at <Strong>[privacy contact email]</Strong>.
      </P>
      <P>
        If you’re in the EU/EEA and believe we’ve mishandled your data, you also have the right
        to lodge a complaint with your national data protection authority — for example{" "}
        <Strong>Integritetsskyddsmyndigheten (IMY)</Strong> if you’re in Sweden, or the
        equivalent authority where you live.
      </P>
    </LegalLayout>
  );
}
