-- 0011_course_knowledge.sql
-- Persistent course knowledge: uploaded course documents (syllabi, schedules,
-- assessment guides) turned into structured, source-traceable academic data.
--
-- The core distinction this schema exists to enforce (docs/PLAN.md §40.3):
-- a fact extracted from a document and a suggestion generated by the AI must
-- never be representable as the same kind of row. Every table below that
-- holds extracted information carries `confidence` and `verified_by_user` —
-- there is deliberately no "recommendation" column on any of them. AI-written
-- planning suggestions (prep timelines) are proposed through the existing
-- advisor propose/confirm path (`plannerCommandSchema`), not stored as if
-- they were course facts.
--
-- An assessment is not a new parallel "thing the planner schedules". It is a
-- `tasks` row (the planner already reads deadline/estimated_minutes/status
-- from `tasks`) plus an `assessment_details` row holding the extra syllabus
-- metadata `tasks` has no reason to carry. One source of truth for "what has
-- to be scheduled", same as §13's to-dos are `tasks` rather than a second list.

-- ------------------------------------------------------------- documents ---

create table public.course_documents (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users(id) on delete cascade,
  course_id          uuid not null references public.courses(id) on delete cascade,
  file_name          text not null,
  file_size          bigint not null,
  mime_type          text not null,
  -- Path inside the `course-documents` storage bucket. Always
  -- `${user_id}/...` — see the storage policy below, which is what makes that
  -- prefix load-bearing rather than a convention.
  storage_path       text not null unique,
  document_type      text not null default 'other',
  processing_status  text not null default 'pending',
  processing_error   text,
  uploaded_at        timestamptz not null default now(),
  processed_at       timestamptz,

  constraint course_documents_file_name_not_blank check (length(trim(file_name)) > 0),
  constraint course_documents_file_size_positive check (file_size > 0),
  constraint course_documents_type_valid check (
    document_type in ('syllabus', 'schedule', 'assessment_guide', 'reading_list', 'other')
  ),
  constraint course_documents_status_valid check (
    processing_status in ('pending', 'processing', 'completed', 'failed')
  )
);

create index course_documents_course_idx on public.course_documents (course_id);
create index course_documents_user_idx on public.course_documents (user_id);

-- ---------------------------------------------------------- requirements ---
-- Everything from a document that is not itself a scheduled deadline:
-- readings, topics, exam format, grading rules, policies.

create table public.course_requirements (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  course_id     uuid not null references public.courses(id) on delete cascade,
  -- set null, not cascade: deleting the source document must not silently
  -- delete a fact the student has already verified against it.
  document_id   uuid references public.course_documents(id) on delete set null,
  type          text not null,
  title         text not null,
  description   text,
  source_page   integer,
  source_text   text,
  confidence    text not null default 'medium',
  verified_by_user boolean not null default false,
  created_at    timestamptz not null default now(),

  constraint course_requirements_title_not_blank check (length(trim(title)) > 0),
  constraint course_requirements_type_valid check (
    type in ('reading', 'topic', 'exam_format', 'grading', 'policy', 'other')
  ),
  constraint course_requirements_confidence_valid check (confidence in ('high', 'medium', 'low')),
  constraint course_requirements_source_page_positive check (source_page is null or source_page > 0)
);

create index course_requirements_course_idx on public.course_requirements (course_id);
create index course_requirements_document_idx on public.course_requirements (document_id);

-- ------------------------------------------------------- assessment detail ---
-- 1:1 with a `tasks` row. `tasks` already owns deadline / estimated_minutes /
-- status, which is what the planner reads — this table only adds what a
-- syllabus states that a task otherwise has no column for.

create table public.assessment_details (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  task_id           uuid not null unique references public.tasks(id) on delete cascade,
  course_id         uuid not null references public.courses(id) on delete cascade,
  document_id       uuid references public.course_documents(id) on delete set null,
  weight_percent    numeric(5, 2),
  word_count        integer,
  assessment_format text,
  source_page       integer,
  source_text       text,
  confidence        text not null default 'medium',
  verified_by_user  boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint assessment_details_weight_range check (
    weight_percent is null or (weight_percent >= 0 and weight_percent <= 100)
  ),
  constraint assessment_details_word_count_positive check (word_count is null or word_count > 0),
  constraint assessment_details_format_valid check (
    assessment_format is null
    or assessment_format in ('individual', 'group', 'presentation', 'exam', 'other')
  ),
  constraint assessment_details_confidence_valid check (confidence in ('high', 'medium', 'low')),
  constraint assessment_details_source_page_positive check (source_page is null or source_page > 0)
);

create index assessment_details_course_idx on public.assessment_details (course_id);
create index assessment_details_document_idx on public.assessment_details (document_id);

create trigger assessment_details_set_updated_at
  before update on public.assessment_details
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------- milestones ---
-- Dates that matter but are not themselves a scheduled piece of work: reading
-- week, an assessment period opening, a draft deadline mentioned in passing.

create table public.course_milestones (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  course_id     uuid not null references public.courses(id) on delete cascade,
  document_id   uuid references public.course_documents(id) on delete set null,
  title         text not null,
  milestone_date date not null,
  type          text not null default 'other',
  description   text,
  source_page   integer,
  source_text   text,
  confidence    text not null default 'medium',
  verified_by_user boolean not null default false,
  created_at    timestamptz not null default now(),

  constraint course_milestones_title_not_blank check (length(trim(title)) > 0),
  constraint course_milestones_type_valid check (
    type in ('teaching_period', 'reading_week', 'assessment_period', 'exam_period', 'other')
  ),
  constraint course_milestones_confidence_valid check (confidence in ('high', 'medium', 'low')),
  constraint course_milestones_source_page_positive check (source_page is null or source_page > 0)
);

create index course_milestones_course_date_idx on public.course_milestones (course_id, milestone_date);

-- ------------------------------------------------------- knowledge updates ---
-- A record of what changed when a course document is re-uploaded and a field
-- disagrees with what is already stored. Never applied silently — see
-- `docs/PLAN.md` §40.13: the student reviews and confirms before anything
-- already-scheduled is touched.

create table public.course_knowledge_updates (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  course_id    uuid not null references public.courses(id) on delete cascade,
  document_id  uuid references public.course_documents(id) on delete set null,
  change_type  text not null,
  field_label  text not null,
  old_value    text,
  new_value    text,
  impact       text,
  resolved     boolean not null default false,
  created_at   timestamptz not null default now(),

  constraint course_knowledge_updates_type_valid check (
    change_type in (
      'deadline_changed', 'weight_changed', 'requirement_added',
      'requirement_removed', 'milestone_changed', 'other'
    )
  )
);

create index course_knowledge_updates_course_idx on public.course_knowledge_updates (course_id)
  where resolved = false;

-- ------------------------------------------------------------------- RLS ---

alter table public.course_documents        enable row level security;
alter table public.course_requirements     enable row level security;
alter table public.assessment_details      enable row level security;
alter table public.course_milestones       enable row level security;
alter table public.course_knowledge_updates enable row level security;

create policy "course_documents_own_rows" on public.course_documents
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "course_requirements_own_rows" on public.course_requirements
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "assessment_details_own_rows" on public.assessment_details
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "course_milestones_own_rows" on public.course_milestones
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "course_knowledge_updates_own_rows" on public.course_knowledge_updates
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- --------------------------------------------------------------- storage ---
-- Original documents are never discarded (§40.1) — kept in a private bucket,
-- one folder per user, so the same `auth.uid() = user_id` shape RLS uses
-- everywhere else applies here via the path prefix.

insert into storage.buckets (id, name, public)
values ('course-documents', 'course-documents', false)
on conflict (id) do nothing;

create policy "course_documents_storage_own_folder" on storage.objects
  for all to authenticated
  using (bucket_id = 'course-documents' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'course-documents' and (storage.foldername(name))[1] = auth.uid()::text);
